/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/user/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그아웃
     * @description Security 로그아웃 필터를 실행한다.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/reissue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * AccessToken 재발급 요청
     * @description 만료된 AccessToken 재발급을 요청한다.
     */
    post: operations['issueAccessToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/task': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 할 일 추가
     * @description 할 일을 생성한다.
     */
    post: operations['create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/collect': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 모음 생성
     * @description 새로운 모음을 생성한다.
     */
    post: operations['createCollect'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/collect/{collectId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * 모음 삭제
     * @description collectId에 해당하는 모음을 삭제한다.
     */
    delete: operations['deleteCollect'];
    options?: never;
    head?: never;
    /**
     * 모음 수정
     * @description collectId에 해당하는 모음의 이름/카테고리를 수정한다.
     */
    patch: operations['updateCollect'];
    trace?: never;
  };
  '/v1/user/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 사용자 정보
     * @description 현재 로그인한 사용자의 정보를 반환한다.
     */
    get: operations['getUser'];
    put?: never;
    post?: never;
    /**
     * 회원탈퇴
     * @description 서비스를 탈퇴한다.
     */
    delete: operations['withdraw'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/task/collections/{collectionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모음별 Task 전체 조회
     * @description collectionId에 속한 Task를 전부 조회한다.
     */
    get: operations['listByCollection'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/collect/select': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 모음 선택 목록 조회
     * @description 할 일 추가 화면에서 '담을 모음 선택'에 사용할 모음 목록(id, 이름)을 조회한다.
     */
    get: operations['listCollectSelectOptions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/collect/category': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 카테고리별 모음 조회 (무한 스크롤) */
    get: operations['listByCategory'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/collect/all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 모음 전체 조회 (무한 스크롤) */
    get: operations['listAll'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ApiResponseString: {
      isSuccess?: boolean;
      code?: string;
      message?: string;
      result?: string;
    };
    TaskCreateRequest: {
      /** Format: int64 */
      collectionId: number;
      title: string;
      link?: string;
      memo?: string;
    };
    ApiResponseTaskResponse: {
      isSuccess?: boolean;
      code?: string;
      message?: string;
      result?: components['schemas']['TaskResponse'];
    };
    TaskResponse: {
      /** Format: int64 */
      taskId?: number;
      /** Format: int64 */
      collectionId?: number;
      title?: string;
      link?: string;
      memo?: string;
      status?: boolean;
      inout?: boolean;
    };
    CollectionCreateRequest: {
      name: string;
      /** @enum {string} */
      category:
        | '맛집'
        | '취미'
        | '여행'
        | '재테크'
        | '쇼핑'
        | '운동'
        | '커리어'
        | '자기개발'
        | '꿀팁'
        | '기타';
    };
    ApiResponseCollectionResponse: {
      isSuccess?: boolean;
      code?: string;
      message?: string;
      result?: components['schemas']['CollectionResponse'];
    };
    CollectionResponse: {
      /** Format: int64 */
      collectionId?: number;
      name?: string;
      /** @enum {string} */
      category?:
        | '맛집'
        | '취미'
        | '여행'
        | '재테크'
        | '쇼핑'
        | '운동'
        | '커리어'
        | '자기개발'
        | '꿀팁'
        | '기타';
      thumbnails?: string[];
    };
    CollectionUpdateRequest: {
      name: string;
      /** @enum {string} */
      category:
        | '맛집'
        | '취미'
        | '여행'
        | '재테크'
        | '쇼핑'
        | '운동'
        | '커리어'
        | '자기개발'
        | '꿀팁'
        | '기타';
    };
    ApiResponseUserResponse: {
      isSuccess?: boolean;
      code?: string;
      message?: string;
      result?: components['schemas']['UserResponse'];
    };
    UserResponse: {
      socialName?: string;
      nickname?: string;
      email?: string;
      profileImageUrl?: string;
    };
    ApiResponseListTaskResponse: {
      isSuccess?: boolean;
      code?: string;
      message?: string;
      result?: components['schemas']['TaskResponse'][];
    };
    ApiResponseListCollectionSimpleResponse: {
      isSuccess?: boolean;
      code?: string;
      message?: string;
      result?: components['schemas']['CollectionSimpleResponse'][];
    };
    CollectionSimpleResponse: {
      /** Format: int64 */
      collectionId?: number;
      name?: string;
    };
    ApiResponseSliceCollectionResponse: {
      isSuccess?: boolean;
      code?: string;
      message?: string;
      result?: components['schemas']['SliceCollectionResponse'];
    };
    PageableObject: {
      /** Format: int64 */
      offset?: number;
      sort?: components['schemas']['SortObject'];
      /** Format: int32 */
      pageNumber?: number;
      /** Format: int32 */
      pageSize?: number;
      unpaged?: boolean;
      paged?: boolean;
    };
    SliceCollectionResponse: {
      first?: boolean;
      last?: boolean;
      /** Format: int32 */
      size?: number;
      content?: components['schemas']['CollectionResponse'][];
      /** Format: int32 */
      number?: number;
      sort?: components['schemas']['SortObject'];
      /** Format: int32 */
      numberOfElements?: number;
      pageable?: components['schemas']['PageableObject'];
      empty?: boolean;
    };
    SortObject: {
      empty?: boolean;
      unsorted?: boolean;
      sorted?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  issueAccessToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseString'];
        };
      };
    };
  };
  create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseTaskResponse'];
        };
      };
    };
  };
  createCollect: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CollectionCreateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseCollectionResponse'];
        };
      };
    };
  };
  deleteCollect: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collectId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseString'];
        };
      };
    };
  };
  updateCollect: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collectId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CollectionUpdateRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseCollectionResponse'];
        };
      };
    };
  };
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseUserResponse'];
        };
      };
    };
  };
  withdraw: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseString'];
        };
      };
    };
  };
  listByCollection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collectionId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListTaskResponse'];
        };
      };
    };
  };
  listCollectSelectOptions: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseListCollectionSimpleResponse'];
        };
      };
    };
  };
  listByCategory: {
    parameters: {
      query: {
        category:
          | '맛집'
          | '취미'
          | '여행'
          | '재테크'
          | '쇼핑'
          | '운동'
          | '커리어'
          | '자기개발'
          | '꿀팁'
          | '기타';
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseSliceCollectionResponse'];
        };
      };
    };
  };
  listAll: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['ApiResponseSliceCollectionResponse'];
        };
      };
    };
  };
}
